In [6]:
import pandas as pd
import numpy as np
from sklearn.tree import DecisionTreeClassifier
from sklearn.metrics import accuracy_score

In [7]:
df_train = pd.read_csv('train.csv', index_col='id')
df_test = pd.read_csv('test.csv', index_col='id')

In [8]:
import warnings

warnings.filterwarnings('ignore')

In [10]:
df_train.head()

class  cap-diameter cap-shape cap-surface cap-color does-bruise-or-bleed  \
id                                                                            
0      e          8.80         f           s         u                    f   
1      p          4.51         x           h         o                    f   
2      e          6.94         f           s         b                    f   
3      e          3.88         f           y         g                    f   
4      e          5.85         x           l         w                    f   

   gill-attachment gill-spacing gill-color  stem-height  ...  stem-root  \
id                                                       ...              
0                a            c          w         4.51  ...        NaN   
1                a            c          n         4.79  ...        NaN   
2                x            c          w         6.85  ...        NaN   
3                s          NaN          g         4.16  ...        NaN   
4                d          NaN          w         3.37  ...        NaN   

   stem-surface stem-color veil-type veil-color has-ring ring-type  \
id                                                                   
0           NaN          w       NaN        NaN        f         f   
1             y          o       NaN        NaN        t         z   
2             s          n       NaN        NaN        f         f   
3           NaN          w       NaN        NaN        f         f   
4           NaN          w       NaN        NaN        f         f   

   spore-print-color habitat season  
id                                   
0                NaN       d      a  
1                NaN       d      w  
2                NaN       l      w  
3                NaN       d      u  
4                NaN       g      a  

[5 rows x 21 columns]

In [11]:
df_train.isnull().sum()

class                         0
cap-diameter                  4
cap-shape                    40
cap-surface              671023
cap-color                    12
does-bruise-or-bleed          8
gill-attachment          523936
gill-spacing            1258435
gill-color                   57
stem-height                   0
stem-width                    0
stem-root               2757023
stem-surface            1980861
stem-color                   38
veil-type               2957493
veil-color              2740947
has-ring                     24
ring-type                128880
spore-print-color       2849682
habitat                      45
season                        0
dtype: int64

In [12]:
X_train = df_train.drop(df_train.columns[0], axis=1)
Y_train = df_train[df_train.columns[0]]
X_test = df_test.drop(df_test.columns[0], axis=1)
Y_test = df_test[df_test.columns[0]]


In [13]:
Y_train[Y_train == 'e'] = 0

Y_train[Y_train == 'p'] = 1

Y_test[Y_test == 'e'] = 0

Y_test[Y_test == 'p'] = 1


In [53]:
#hotencoding

import csv
"""DAta colums that need hot encoding
id,class,cap-shape,cap-surface,cap-color,does-bruise-or-bleed,gill-attachment,gill-spacing,gill-color,stem-root,stem-surface,
stem-color,veil-type,veil-color,has-ring,ring-type,spore-print-color,habitat,season
"""
train_DataFrame = pd.read_csv('train.csv', index_col= 'id')
train_DataFrame.columns
#these should be all the categorical columns that need to be encoded
encode_columns = train_DataFrame[['class', 'cap-shape', 'cap-surface', 'cap-color', 'does-bruise-or-bleed', 'gill-attachment',
                                  'gill-spacing','gill-color','stem-root','stem-surface', 'stem-color','veil-type', 
                                  'veil-color','has-ring','ring-type','spore-print-color','habitat','season']]

#rest of code in next code cell


In [59]:
from sklearn.preprocessing import MultiLabelBinarizer
#encode_columns.head()
mlb = MultiLabelBinarizer()
encoded = mlb.fit_transform(encode_columns)
print(len(train_DataFrame.columns))
print(len(encode_columns.columns))
print(encoded)
print(len(encoded))



21
18
[[0 1 0 1 0 0 0 0 0 0 1 0 0 0 0 0 1 0 0 0 0]
 [1 1 0 1 0 1 0 0 1 0 0 0 0 0 1 0 1 0 0 0 0]
 [1 1 0 1 0 1 1 0 0 0 0 0 0 0 1 1 1 0 1 0 0]
 [1 1 0 1 0 0 0 0 0 0 1 0 0 1 1 1 0 0 0 0 0]
 [1 0 1 0 1 1 0 0 0 1 1 0 0 1 0 1 1 0 1 0 0]
 [1 1 0 1 0 1 0 1 1 1 1 1 1 0 0 0 0 1 0 0 0]
 [1 1 0 1 0 0 0 1 0 1 1 0 1 0 1 0 1 0 0 0 0]
 [1 0 0 1 0 0 0 1 0 1 1 0 0 1 0 1 0 0 0 0 0]
 [1 0 0 0 0 1 0 0 0 0 0 1 0 1 0 1 1 1 0 0 0]
 [1 1 0 1 0 1 1 0 0 0 0 1 0 0 0 1 1 1 1 0 0]
 [1 0 0 1 0 1 0 0 0 0 1 1 0 1 0 1 1 1 0 0 0]
 [1 0 0 0 0 1 0 0 0 1 1 0 0 0 1 0 0 1 0 1 1]
 [1 0 0 1 0 1 0 0 0 1 1 0 0 1 0 1 0 0 0 1 0]
 [1 1 0 0 0 0 0 1 1 1 0 0 1 0 0 1 1 0 0 0 0]
 [1 0 0 0 0 1 0 1 0 1 0 0 1 0 1 1 0 1 0 0 1]
 [1 0 0 1 0 1 0 0 0 1 1 0 1 1 1 1 1 1 0 0 0]
 [0 1 1 0 0 0 0 0 1 1 0 0 0 0 0 0 0 1 0 0 0]
 [0 1 0 0 0 1 0 0 0 0 0 0 1 1 0 0 1 0 0 0 0]]
18


In [ ]:
def train_using_entropy(X, y):
    # Decision tree with entropy
    dft_entropy = DecisionTreeClassifier(
        criterion="entropy", random_state=100,
        max_depth=3, min_samples_leaf=5)

    # Performing training
    dft_entropy.fit(X, y)
    return dft_entropy

In [ ]:
y_pred = train_using_entropy(X_train, Y_train).predict(X_test)
print("Accuracy : ", accuracy_score(Y_test, y_pred)*100)

In [ ]:
import xgboost as xgb
# define data_dmatrix
#https://gist.github.com/pb111/cc341409081dffa5e9eaf60d79562a03
data_dmatrix = xgb.DMatrix(data=X_train,label=Y_train)

In [ ]:
# import XGBClassifier
from xgboost import XGBClassifier


# declare parameters
params = {
            'objective':'binary:logistic',
            'max_depth': 4,
            'alpha': 10,
            'learning_rate': 1.0,
            'n_estimators':100
        }
            
            
            
# instantiate the classifier 
xgb_clf = XGBClassifier(**params)



# fit the classifier to the training data
xgb_clf.fit(X_train, Y_train)

In [ ]:
# make predictions on test data
y_pred2 = xgb_clf.predict(X_test)

In [ ]:

print('XGBoost model accuracy score: {0:0.4f}'. format(accuracy_score(Y_test, y_pred)))